USE [master]
GO

/****** Object:  Database [TestEvert]    Script Date: 5/02/2023 8:07:29 p. m. ******/
CREATE DATABASE [TestEvert]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestEvert', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestEvert.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestEvert_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestEvert_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestEvert].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestEvert] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestEvert] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestEvert] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestEvert] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestEvert] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestEvert] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestEvert] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestEvert] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestEvert] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestEvert] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestEvert] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestEvert] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestEvert] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestEvert] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestEvert] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestEvert] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestEvert] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestEvert] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestEvert] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestEvert] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestEvert] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestEvert] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestEvert] SET RECOVERY FULL 
GO

ALTER DATABASE [TestEvert] SET  MULTI_USER 
GO

ALTER DATABASE [TestEvert] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestEvert] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestEvert] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestEvert] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestEvert] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestEvert] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestEvert] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TestEvert] SET  READ_WRITE 
GO


USE [TestEvert]
GO

/****** Object:  Table [dbo].[Employees]    Script Date: 5/02/2023 8:07:03 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employees](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeeName] [varchar](50) NOT NULL,
	[EmployeeLastName] [varchar](50) NOT NULL,
	[DateOfBird] [date] NULL,
	[EstadoCivil] [int] NULL,
	[Brothers] [bit] NULL,
	[PhotoFileName] [nvarchar](500) NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO